style = {
    "font": {
        "file": "PyCleanUI\Assets\Roboto-Bold.ttf",
        "size": 16,
        "color": [95, 95, 95],
    },
    "background": {
        "color": [255, 255, 255],
    },
    "button": {
        "padx": 25,
        "normal": [235, 235, 235],
        "hover": [215, 215, 215],
        "click": [195, 195, 195],
    },
    "input": {
        "width": 200,
        "active": [230, 230, 230],
        "inactive": [235, 235, 235],
    },
    "cursors": {
        "text": {
            "width": 2,
            "color": [95, 95, 95]
        },
        "normal": ( # size 24x32
            "X                       ",
            "XX                      ",
            "X.X                     ",
            "X..X                    ",
            "X...X                   ",
            "X....X                  ",
            "X.....X                 ",
            "X......X                ",
            "X.......X               ",
            "X........X              ",
            "X.........X             ",
            "X..........X            ",
            "X...........X           ",
            "X............X          ",
            "X.......XXXXXXX         ",
            "X...X...X               ",
            "X..XXX...X              ",
            "X.X  X...X              ",
            "XX    X...X             ",
            "X     X...X             ",
            "       X...X            ",
            "       X...X            ",
            "        X...X           ",
            "        X...X           ",
            "         XXX            ",
            "                        ",
            "                        ",
            "                        ",
            "                        ",
            "                        ",
            "                        ",
            "                        ",
        ),
        "button": ( #size 24x24
            "        XX              ",
            "       X..X             ",
            "       X..X             ",
            "       X..X             ",
            "       X..X             ",
            "       X..XXX           ",
            "       X..X..XXX        ",
            "       X..X..X..XXX     ",
            "       X..X..X..X..X    ",
            "       X..X..X..X..X    ",
            "       X..X..X..X..X    ",
            "       X...........X    ",
            "   XX  X...........X    ",
            "  X..XXX...........X    ",
            "  X....X...........X    ",
            "   X...............X    ",
            "   XX..............X    ",
            "    XX.............X    ",
            "     XX...........XX    ",
            "      X...........X     ",
            "      XX.........XX     ",
            "       XX.......XX      ",
            "        XXX...XXX       ",
            "          XXXXX         ",

        ),
        "input": ( #sized 8x24
            "ooo  ooo",
            "  oooo  ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "  oooo  ",
            "ooo  ooo",
            "        ",
            "        ",
            "        ",
            "        ",
    ),
    },
    "padding": 10
}
