STYLE = {
    "font": {
        "type": "Segoe UI Regular",
        "size": 32,
        "color": [200, 200, 200],
    },
    "background": {
        "color": [40, 40, 40],
    },
    "button": {
        "normal": [100, 100, 100],
        "hover": [80, 80, 80],
        "click": [60, 60, 60],
        "disabled": [80, 80, 80],
    },
    "cursors": {
        "normal": ( # size 24x32
            "X                       ",
            "XX                      ",
            "X.X                     ",
            "X..X                    ",
            "X...X                   ",
            "X....X                  ",
            "X.....X                 ",
            "X......X                ",
            "X.......X               ",
            "X........X              ",
            "X.........X             ",
            "X..........X            ",
            "X...........X           ",
            "X............X          ",
            "X.......XXXXXXX         ",
            "X...X...X               ",
            "X..XXX...X              ",
            "X.X  X...X              ",
            "XX    X...X             ",
            "X     X...X             ",
            "       X...X            ",
            "       X...X            ",
            "        X...X           ",
            "        X...X           ",
            "         XXX            ",
            "                        ",
            "                        ",
            "                        ",
            "                        ",
            "                        ",
            "                        ",
            "                        ",
        ),
        "button": ( #size 24x24
            "        XX              ",
            "       X..X             ",
            "       X..X             ",
            "       X..X             ",
            "       X..X             ",
            "       X..XXX           ",
            "       X..X..XXX        ",
            "       X..X..X..XXX     ",
            "       X..X..X..X..X    ",
            "       X..X..X..X..X    ",
            "       X..X..X..X..X    ",
            "       X...........X    ",
            "   XX  X...........X    ",
            "  X..XXX...........X    ",
            "  X....X...........X    ",
            "   X...............X    ",
            "   XX..............X    ",
            "    XX.............X    ",
            "     XX...........XX    ",
            "      X...........X     ",
            "      XX.........XX     ",
            "       XX.......XX      ",
            "        XXX...XXX       ",
            "          XXXXX         ",

        ),
        "input": ( #sized 8x24
            "ooo  ooo",
            "  oooo  ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "   oo   ",
            "  oooo  ",
            "ooo  ooo",
            "        ",
            "        ",
            "        ",
            "        ",
    ),
    },
    "padding": 10
}
